spring:
  devtools:
    thymelaef:
      cache: false
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost/xfra_new?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;allowMultiQueries=true
    username: emsone
    password: dbghtmxm1!
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mvc:
    view:
      suffix: .html
    static-path-pattern: /static/**
    static-location: /resources/**
mybatis:
  config-location: classpath:config/config-mybatis.xml
  check-config-location: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          trace
jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
